name: Deploy-to-EC2

on:
  push:
    branches:
    - main

jobs:
  deploy:
    environment: git-build
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/discord"
      
      - name: Setup Agent
        run: exec ssh-agent
        
      - name: Add Keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: ssh-add <<< "${SSH_PRIVATE_KEY}"
        
      - name: Connect to EC2
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: "ubuntu"
        run: ssh -i $REMOTE_USER@$REMOTE_HOST
        
      - name: Terminate Old Screen
        run: screen -X quit
        
      - name: Spin up New Screen
        run: |
          screen
           
      - name: Change Directory
        run: cd discord/src/
        
      - name: Restart Application          
        run: python3 app.py
            
